### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by wylieswanson** [ownaginatious/mixpanel-jql#1]
It would be great to see some additional examples, particularly some examples that would 'out-of-the-box' work for even a most basic MixPanel setup.  It would also be great if you could also pass arbitrary code to JQL, rather then JQL and associated functions always being used.

**Comment by ownaginatious** [comment]
Thanks for the feedback! I added a couple of examples that should work with pretty much any Mixpanel setup.

Not sure what you mean by the second thing; arbitrary JavaScript functions can be passed in into most places where it's relevant, such as the `accumulator` keyword argument in `.group_by_user`.

``` python
...
.group_by_user(
    keys=[
        "new Date(e.time).toISOString().split('T')[0]",
        "e.property.C"
    ],
    accumulator="function(){ return 1;}")
...
```

Please open another issue if you meant something else.
