### ISSUE TITLE
An option on the JQL constructor to do an inner join on People and Events

### ISSUE THREAD

**Issue by arawlin2** [ownaginatious/mixpanel-jql#11]
The existing code if People and Events is true results in a full join, ` join(Events(params), People()).`

Would be nice to have an option to do an inner join like this

` join(Events(params), People(),{type:'inner'})`

This can be used to avoid errors when the map function tries to read from an event that isn't present in the output of a full join.

> Uncaught exception TypeError: Cannot read property 'time' of undefined
>   return {"distinct_id":e.distinct_id,"time":e.event.time
>                                                                                             ^
> Stack trace:
> TypeError: Cannot read property 'time' of undefined

**Comment by arawlin2** [comment]
#12 , join_type can now be specified.  Default behavior is to do full join, which was the behavior in the previous code.

**Comment by ownaginatious** [comment]
Why did you close this?

**Comment by arawlin2** [comment]
Not sure that I meant to.  I think I just meant to do the pull request #12

On Oct 19, 2017 4:45 PM, "Dillon Dixon" <notifications@github.com> wrote:

Why did you close this?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/ownaginatious/mixpanel-jql/issues/11#issuecomment-338032489>,
or mute the thread

**Comment by ownaginatious** [comment]
Ah, LGTM :+1: Just merged and will push a new version to PyPI soon.

**Comment by ownaginatious** [comment]
Ended up fixing support for all parameters to `Event(...)` and `User(...)` instead. See this PR [here](https://github.com/ownaginatious/mixpanel-jql/pull/13).

**Comment by ownaginatious** [comment]
Now live in version `0.4` on PyPI.
