### ISSUE TITLE
mixpanel_jql.exceptions.InvalidJavaScriptText

### ISSUE THREAD

**Issue by guilhermecomum** [ownaginatious/mixpanel-jql#17]
Hi, first of all thanks for this project!

I'm trying to run the first example and I'm getting:
`mixpanel_jql.exceptions.InvalidJavaScriptText: Must be a text type (str, unicode) or wrapped as raw(str||unicode)`

I'm runnning Python 3.6.5 on Ubuntu 18.04

**Comment by ownaginatious** [comment]
Hey, thanks for pointing that out! I accidentally broke that and didn't notice... and it has been there for an embarrassingly long time :| I'll push a new version to PyPI soon!

**Comment by ownaginatious** [comment]
Fixed in version `0.5.1`!
