### ISSUE TITLE
Filter by words

### ISSUE THREAD

**Issue by jedileesang** [ownaginatious/mixpanel-jql#19]
Hello,

I am trying to export rows has logged out data. 
There is current_url property and this include that information.
However, indexOf, slice, search, find, and include functions don't work.

```python
query = JQL(
    api_secret,
    events=Events({
        'from_date': "2020-11-03",
        'to_date': "2020-11-03"
    })
).filter(
    'e.properties["current_url"].indexOf("loggedout") > -1  ' 
)
```
It will be helpful if these types of examples included.

**Comment by ownaginatious** [comment]
Hi there!

I believe the property `current_url` is a default Mixpanel property. Therefore, to access it, you should include a `$` prefix:

```javascript
e.properties["$current_url"].indexOf("loggedout") > -1
```

Keep in mind, all this project does is provide a nice programming interface for generating a JQL query, which is JavaScript. It does not interpret any of it to know if it's "correct" other than being syntactically valid JavaScript. So I don't think putting an exhaustive list of examples of different JQL event properties in the `README.md` here makes any sense.

I just read Mixpanel's [official JQL documentation](https://developer.mixpanel.com/docs/jql-language-reference) to figure out the above 😉

**Comment by jedileesang** [comment]
> Hi there!
> 
> I believe the property `current_url` is a default Mixpanel property. Therefore, to access it, you should include a `$` prefix:
> 
> ```js
> e.properties["$current_url"].indexOf("loggedout") > -1
> ```
> 
> Keep in mind, all this project does is provide a nice programming interface for generating a JQL query, which is JavaScript. It does not interpret any of it to know if it's "correct" other than being syntactically valid JavaScript. So I don't think putting an exhaustive list of examples of different JQL event properties in the `README.md` here makes any sense.
> 
> I just read Mixpanel's [official JQL documentation](https://developer.mixpanel.com/docs/jql-language-reference) to figure out the above 😉

Thank you soooooo much!! that was it.
I am reading the official JQL documentation now.
Thank you again for your help!!!

**Comment by ownaginatious** [comment]
No problem; glad that worked! 😄
