### ISSUE TITLE
io.UnsupportedOperation: seek

### ISSUE THREAD

**Issue by frankchen07** [ownaginatious/mixpanel-jql#2]
In this portion:

```
for row in query.send():
    date = row['key']
    value = row['value']
    print("[%s] => %d" % (date, value))
```

It errors out with (only partial/tail end of the error):

```
"/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 296, in _read
self.fileobj.seek(0, 2)     # Seek to end of file                                                                                                                                           
io.UnsupportedOperation: seek
```

The query object is being saved (as a Mixpanel JQL object), and the `send()` function renders it as a generator send object, but iterating through it seems to cause problems. StackOverFlow says that `seek(0, 2)` (which means searching from the end of a document) is not supported in Python 2.7, and is only supported in Python 3+. 

Any thoughts?

**Comment by ownaginatious** [comment]
Thanks for pointing this out! A little embarrassing that I somehow forgot to ever actually try using the library with Python 2... heh

Anyway, while there isn't really a solution to the `seek` and `gzip.GzipFile` thing, I found that I was "reinventing the wheel a bit"; the underlying `requests` library can handle the decompression transparently while still maintaining streamability, if wrapped appropriately.

I just pushed a new version (0.3) where the examples should work properly under both Python 2 and 3.
