### ISSUE TITLE
Filter not applied to Join

### ISSUE THREAD

**Issue by chesstrian** [ownaginatious/mixpanel-jql#3]
Hi
I have this:

``` python
params = {
    'from_date': '2016-06-01',
    'to_date': '2016-06-25'
}
query = JQL(api, params, people=True).filter('e.name == "Any event"')

print query.query_plan()
```

`people=True` makes a join between events and people, but when I apply the filter, such filter is applied only to events. How can I implement the filter for the join?.

If `filter` method is used, `events=False` and `people=True` arguments are ignored.

Thanks in advance.

**Comment by ownaginatious** [comment]
Hi there! The `e` is only a name for the argument to the filter and isn't necessarily an event. For example, consider a join between people and events like you mentioned. See the join-part of the Mixpanel JQL documentation [here](https://mixpanel.com/help/reference/jql/api-reference#api/join).

Based on that, if we were to modify your query, the `e` would actually function as the `tuple` argument.

``` python
params = {
    'from_date': '2016-06-01',
    'to_date': '2016-06-25'
}
query = JQL(api, params, events=True, people=True).filter('e.event.name == "Any event"')

print query.query_plan()
```

I could change things such that the argument name gets changed to `user` for people only, or `tuple` for the join, but that would potentially break any queries people are already using this library for.

Please clarify if this isn't what you were referring to. Thanks!

**Comment by chesstrian** [comment]
The following code

``` python
params = {
    'from_date': '2016-06-01',
    'to_date': '2016-06-25'
}
query = JQL(api, params, people=True)

print query.query_plan()
```

shows

``` js
function main() { return join(Events(params), People()); }
```

but the following code

``` python
params = {
    'from_date': '2016-06-01',
    'to_date': '2016-06-25'
}
query = JQL(api, params, people=True).filter('e.user && e.event')

print query.query_plan()
```

returns

``` js
function main() { return Events(params).filter(function(e){return e.user && e.event}); }
```

See the difference before the filter, there is no join in the second case.

**Comment by ownaginatious** [comment]
Thanks for the clarification, I see what you mean now. That's pretty obscure, but definitely the wrong behaviour! Good catch! I'll have to get around to writing unit tests to catch things like this one day...

I've corrected the error and uploaded a new version to PyPI (`0.3.post4`).

**Comment by chesstrian** [comment]
Works perfect!, thanks a lot.
