### ISSUE TITLE
Error on map function?

### ISSUE THREAD

**Issue by arawlin2** [ownaginatious/mixpanel-jql#8]
I received this error  "AttributeError: 'JQL' object has no attribute 'raw_filter'"
after running this code
ret = '{"distinct_id":e.distinct_id}'
query = JQL(api_secret, params,events=True,people=True).map(ret)

I forked the repo and updated the map function so that this works, but wanted to make sure I was doing this correctly in the first place.

**Comment by arawlin2** [comment]
Pull req #9

**Comment by ownaginatious** [comment]
Thanks, merged your PR :+1: The fixed version is up on PyPI now: `0.3.post18`

**Comment by arawlin2** [comment]
glad I was able to help.
